[package]
name = "tera-hot"
version = "0.3.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
description = "Hot reload tera template"
license = "MIT"

[dependencies]
log = "0.4"
notify = "4.0"
tera = "1.5"
