[package]
name = "tera-hot"
version = "0.5.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2024"
description = "Hot reload tera template"
license = "MIT"

[dependencies]
log = "0.4"
notify = "8.0"
tera = "1.5"
